<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.17763.0</TargetFramework>
    <WindowsSdkPackageVersion>10.0.17763.46</WindowsSdkPackageVersion>
    <RootNamespace>CS2_AutoAccept</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Description>A program to automatically find and press "ACCEPT" for you, when entering a
      competitive match in CS2.</Description>
    <Copyright>©️ tsgsOFFICIAL - 2026</Copyright>
    <FileVersion>5.2.1.2</FileVersion>
    <AssemblyName>CS2-AutoAccept</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\Release\**" />
    <EmbeddedResource Remove="bin\Release\**" />
    <None Remove="bin\Release\**" />
    <Page Remove="bin\Release\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="background.png" />
    <None Remove="Discord white.png" />
    <None Remove="discord.png" />
    <None Remove="github.png" />
    <None Remove="logo.png" />
    <None Remove="Resources\accept.png" />
    <None Remove="Resources\accept_invite.png" />
    <None Remove="Resources\connect_to_server.png" />
    <None Remove="tsgs.png" />
  </ItemGroup>

  <ItemGroup>
    <Content
      Include="bin\Release\net6.0-windows10.0.17763.0\publish\win-x86\CS2-AutoAccept.deps.json" />
    <Content
      Include="bin\Release\net6.0-windows10.0.17763.0\publish\win-x86\CS2-AutoAccept.runtimeconfig.json" />
    <Content Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\accept.png" />
    <EmbeddedResource Include="Resources\accept_invite.png" />
    <EmbeddedResource Include="Resources\connect_to_server.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Release\net6.0-windows10.0.17763.0\publish\win-x86\**" />
    <None Include="Properties\PublishProfiles\FolderProfile.pubxml.user" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GlobalHotKey" Version="1.1.0" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.11.0.20250507" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="Tesseract.Drawing" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="background.png" />
    <Resource Include="Discord white.png" />
    <Resource Include="discord.png" />
    <Resource Include="github.png" />
    <Resource Include="logo.png" />
    <Resource Include="tsgs.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="tessdata\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>